[package]
name = "atb-types"
version = "0.14.5"
authors = ["Denis Tsai <denistsai@aetheras.io>"]
edition = "2021"

[dependencies]
# #NOTE 1.0.0 is out with features we need, should update when other deps use it
uuidv0_8 = { package =  "uuid", version = "0.8", features = ["serde", "v1", "v4", "v5"], optional = true }
uuidv1 = { package =  "uuid", version = "1", features = ["serde", "v1", "v4", "v5"], optional = true }
chrono = { version = "0.4.21", features = ["serde"] }

jsonwebtoken = {version = "8.1", optional = true }
lazy_static = { version = "1.4", optional = true }
base64 = { version = "0.13", optional = true } 
serde = { version = "1", features = ["derive"], optional = true }
serde_json = { version = "1", optional = true } 

[features]
default = []
all = ["jwt", "uuidv1"]
jwt = [
  "jsonwebtoken",
  "lazy_static",
  "base64",
  "serde",
  "serde_json",
]
