[package]
name = "atb-cli"
version = "0.13.0"
authors = ["Denis Tsai <denistsai@aetheras.io>"]
edition = "2021"

[dependencies]
clap = { version = "3", features = ["derive", "env", "cargo"] }
strum = "0.19.2"
strum_macros = "0.19.2"
chrono = { version = "0.4", features = ["serde"] }
serde = { version = "1", features = ["derive"] }
