[package]
name = "atb-cli"
version = "0.14.4"
authors = ["Denis Tsai <denistsai@aetheras.io>"]
edition = "2021"

[dependencies]
clap = { version = "3", features = ["derive", "env", "cargo"] }
once_cell = "1"
strum = "0.24"
strum_macros = "0.24"
chrono = { version = "0.4.21", features = ["serde"] }
serde = { version = "1", features = ["derive"] }
