[package]
name = "atb-serde-ext"
version.workspace = true
authors.workspace = true
edition.workspace = true
repository.workspace = true

[dependencies]
serde = { version = "1", features = ["derive"] }
base64 = { version = "0.22" }
